//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ChargeBearerType1Code.  ISO2002 ID# _a8PpINp-Ed-ak6NoX_4Aeg_940131843.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ChargeBearerType1Code"/>.
    /// </summary>
    public class ChargeBearerType1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ChargeBearerType1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ChargeBearerType1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ChargeBearerType1Code.BorneByDebtor => "DEBT",
                ChargeBearerType1Code.BorneByCreditor => "CRED",
                ChargeBearerType1Code.Shared => "SHAR",
                ChargeBearerType1Code.FollowingServiceLevel => "SLEV",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
