//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ChequeDelivery1Code.  ISO2002 ID# _a-Usx9p-Ed-ak6NoX_4Aeg_681596924.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ChequeDelivery1Code"/>.
    /// </summary>
    public class ChequeDelivery1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ChequeDelivery1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ChequeDelivery1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ChequeDelivery1Code.MailToDebtor => "MLDB",
                ChequeDelivery1Code.MailToCreditor => "MLCD",
                ChequeDelivery1Code.MailToFinalAgent => "MLFA",
                ChequeDelivery1Code.CourierToDebtor => "CRDB",
                ChequeDelivery1Code.CourierToCreditor => "CRCD",
                ChequeDelivery1Code.CourierToFinalAgent => "CRFA",
                ChequeDelivery1Code.PickUpByDebtor => "PUDB",
                ChequeDelivery1Code.PickUpByCreditor => "PUCD",
                ChequeDelivery1Code.PickUpByFinalAgent => "PUFA",
                ChequeDelivery1Code.RegisteredMailToDebtor => "RGDB",
                ChequeDelivery1Code.RegisteredMailToCreditor => "RGCD",
                ChequeDelivery1Code.RegisteredMailToFinalAgent => "RGFA",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
