//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ClearingChannel2Code.  ISO2002 ID# _a_OEo9p-Ed-ak6NoX_4Aeg_1501459302.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ClearingChannel2Code"/>.
    /// </summary>
    public class ClearingChannel2CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ClearingChannel2Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ClearingChannel2Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ClearingChannel2Code.RealTimeGrossSettlementSystem => "RTGS",
                ClearingChannel2Code.RealTimeNetSettlementSystem => "RTNS",
                ClearingChannel2Code.MassPaymentNetSystem => "MPNS",
                ClearingChannel2Code.BookTransfer => "BOOK",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
