//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ExchangeRateType1Code.  ISO2002 ID# _aksr2Np-Ed-ak6NoX_4Aeg_-75535887.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ExchangeRateType1Code"/>.
    /// </summary>
    public class ExchangeRateType1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ExchangeRateType1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ExchangeRateType1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ExchangeRateType1Code.Spot => "SPOT",
                ExchangeRateType1Code.Sale => "SALE",
                ExchangeRateType1Code.Agreed => "AGRD",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
