//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ExternalDiscountAmountType1Code.  ISO2002 ID# _t7boglkyEeGeoaLUQk__nA_611729510.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ExternalDiscountAmountType1Code"/>.
    /// </summary>
    public class ExternalDiscountAmountType1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ExternalDiscountAmountType1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ExternalDiscountAmountType1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ExternalDiscountAmountType1Code.AdditionalPromotionalDiscount => "APDS",
                ExternalDiscountAmountType1Code.StandingDiscount => "STDS",
                ExternalDiscountAmountType1Code.TermsDiscount => "TMDS",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
