//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ExternalClearingSystemIdentification1Code.  ISO2002 ID# _amVqlNp-Ed-ak6NoX_4Aeg_319823369.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ExternalClearingSystemIdentification1Code"/>.
    /// </summary>
    public class ExternalClearingSystemIdentification1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ExternalClearingSystemIdentification1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ExternalClearingSystemIdentification1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ExternalClearingSystemIdentification1Code.AustrianBankleitzahl => "ATBLZ",
                ExternalClearingSystemIdentification1Code.AustralianBankStateBranchCodeBSB => "AUBSB",
                ExternalClearingSystemIdentification1Code.CanadianPaymentsAssociationPaymentRoutingNumber => "CACPA",
                ExternalClearingSystemIdentification1Code.SwissFinancialInstitutionIdentificationShort => "CHBCC",
                ExternalClearingSystemIdentification1Code.SwissFinancialInstitutionIdentificationLong => "CHSIC",
                ExternalClearingSystemIdentification1Code.CNAPSIdentifier => "CNAPS",
                ExternalClearingSystemIdentification1Code.GermanBankleitzahl => "DEBLZ",
                ExternalClearingSystemIdentification1Code.SpanishDomesticInterbankingCode => "ESNCC",
                ExternalClearingSystemIdentification1Code.UKDomesticSortCode => "GBDSC",
                ExternalClearingSystemIdentification1Code.HelenicBankIdentificationCode => "GRBIC",
                ExternalClearingSystemIdentification1Code.HongKongBankCode => "HKNCC",
                ExternalClearingSystemIdentification1Code.IrishNationalClearingCode => "IENCC",
                ExternalClearingSystemIdentification1Code.IndianFinancialSystemCode => "INFSC",
                ExternalClearingSystemIdentification1Code.ItalianDomesticIdentificationCode => "ITNCC",
                ExternalClearingSystemIdentification1Code.JapanZenginClearingCode => "JPZGN",
                ExternalClearingSystemIdentification1Code.NewZealandNationalClearingCode => "NZNCC",
                ExternalClearingSystemIdentification1Code.PolishNationalClearingCode => "PLKNR",
                ExternalClearingSystemIdentification1Code.PortugueseNationalClearingCode => "PTNCC",
                ExternalClearingSystemIdentification1Code.RussianCentralBankIdentificationCode => "RUCBC",
                ExternalClearingSystemIdentification1Code.SwedenBankgiroClearingCode => "SESBA",
                ExternalClearingSystemIdentification1Code.IBGSortCode => "SGIBG",
                ExternalClearingSystemIdentification1Code.ThaiCentralBankIdentificationCode => "THCBC",
                ExternalClearingSystemIdentification1Code.FinancialInstitutionCode => "TWNCC",
                ExternalClearingSystemIdentification1Code.UnitedStatesRoutingNumberFedwireNACHA => "USABA",
                ExternalClearingSystemIdentification1Code.CHIPSParticipantIdentifier => "USPID",
                ExternalClearingSystemIdentification1Code.SouthAfricanNationalClearingCode => "ZANCC",
                ExternalClearingSystemIdentification1Code.NewZealandRTGSClearingCode => "NZRSA",
                ExternalClearingSystemIdentification1Code.BancoDeMocambiqueRTGS => "MZBMO",
                ExternalClearingSystemIdentification1Code.CrossBorderInterbankPaymentSystem => "CNCIP",
                ExternalClearingSystemIdentification1Code.SouthKoreaCentralBankIdentificationCode => "KRBOK",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
