//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ExternalCashAccountType1Code.  ISO2002 ID# _t7bogVkyEeGeoaLUQk__nA_-2034002224.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ExternalCashAccountType1Code"/>.
    /// </summary>
    public class ExternalCashAccountType1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ExternalCashAccountType1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ExternalCashAccountType1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ExternalCashAccountType1Code.Current => "CACC",
                ExternalCashAccountType1Code.CardAccount => "CARD",
                ExternalCashAccountType1Code.CashPayment => "CASH",
                ExternalCashAccountType1Code.Charges => "CHAR",
                ExternalCashAccountType1Code.CashIncome => "CISH",
                ExternalCashAccountType1Code.Commission => "COMM",
                ExternalCashAccountType1Code.ClearingParticipantSettlementAccount => "CPAC",
                ExternalCashAccountType1Code.LimitedLiquiditySavingsAccount => "LLSV",
                ExternalCashAccountType1Code.Loan => "LOAN",
                ExternalCashAccountType1Code.MarginalLending => "MGLD",
                ExternalCashAccountType1Code.MoneyMarket => "MOMA",
                ExternalCashAccountType1Code.NonResidentExternal => "NREX",
                ExternalCashAccountType1Code.Overdraft => "ODFT",
                ExternalCashAccountType1Code.OverNightDeposit => "ONDP",
                ExternalCashAccountType1Code.OtherAccount => "OTHR",
                ExternalCashAccountType1Code.Settlement => "SACC",
                ExternalCashAccountType1Code.Salary => "SLRY",
                ExternalCashAccountType1Code.Savings => "SVGS",
                ExternalCashAccountType1Code.Tax => "TAXE",
                ExternalCashAccountType1Code.TransactingAccount => "TRAN",
                ExternalCashAccountType1Code.CashTrading => "TRAS",
                ExternalCashAccountType1Code.VirtualAccount => "VACC",
                ExternalCashAccountType1Code.NonResidentForeignCurrencyAccount => "NFCA",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
