//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ExternalTaxAmountType1Code.  ISO2002 ID# _t99_JFkyEeGeoaLUQk__nA_700990481.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ExternalTaxAmountType1Code"/>.
    /// </summary>
    public class ExternalTaxAmountType1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ExternalTaxAmountType1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ExternalTaxAmountType1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ExternalTaxAmountType1Code.CityTax => "CITY",
                ExternalTaxAmountType1Code.CountyTax => "CNTY",
                ExternalTaxAmountType1Code.LocalTax => "LOCL",
                ExternalTaxAmountType1Code.ProvinceTax => "PROV",
                ExternalTaxAmountType1Code.StateTax => "STAT",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
