//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ExternalLocalInstrument1Code.  ISO2002 ID# _ame0gdp-Ed-ak6NoX_4Aeg_-1943783063.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ExternalLocalInstrument1Code"/>.
    /// </summary>
    public class ExternalLocalInstrument1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ExternalLocalInstrument1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ExternalLocalInstrument1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ExternalLocalInstrument1Code.DirectDebitConfirmedElectronicMandate => "DDMC",
                ExternalLocalInstrument1Code.DirectDebitPaperMandateWithPaperAuthorization => "DDMP",
                ExternalLocalInstrument1Code.DirectDebitUnconfirmedElectronicMandate => "DDMU",
                ExternalLocalInstrument1Code.BatchPaymentsAruba => "BPA",
                ExternalLocalInstrument1Code.InstantPaymentsAruba => "IPA",
                ExternalLocalInstrument1Code.CreditTransfers => "TRF",
                ExternalLocalInstrument1Code.NonPreauthorisedDirectDebitAT => "82",
                ExternalLocalInstrument1Code.PreauthorisedDirectDebitAT => "83",
                ExternalLocalInstrument1Code.CashPerPost => "CPP",
                ExternalLocalInstrument1Code.ReturnedCreditTransfers => "RTR",
                ExternalLocalInstrument1Code.TruncatedCreditTransfers => "GST",
                ExternalLocalInstrument1Code.DirectDebits => "DDT",
                ExternalLocalInstrument1Code.ReturnedDirectDebits => "RDD",
                ExternalLocalInstrument1Code.TruncatedChecks => "CHN",
                ExternalLocalInstrument1Code.RevokedCreditTransfers => "STR",
                ExternalLocalInstrument1Code.RevokedDirectDebits => "SDD",
                ExternalLocalInstrument1Code.RevokedReturnedCreditTransfers => "SRT",
                ExternalLocalInstrument1Code.RevokedReturnedDirectDebits => "SRD",
                ExternalLocalInstrument1Code.RevokedTruncatedChecks => "SCN",
                ExternalLocalInstrument1Code.RevokedTruncatedCreditTransfers => "SGT",
                ExternalLocalInstrument1Code.CardClearing => "CARD",
                ExternalLocalInstrument1Code.NonPreauthorisedDirectDebitDE => "05",
                ExternalLocalInstrument1Code.PreauthorisedDirectDebitDE => "04",
                ExternalLocalInstrument1Code.ImageBasedChequeCollection => "ISE",
                ExternalLocalInstrument1Code.PaperlessChequeCollection => "BSE",
                ExternalLocalInstrument1Code.BusinessToBusinessDirectDebit => "58",
                ExternalLocalInstrument1Code.BusinessToCustomerDirectDebit => "19",
                ExternalLocalInstrument1Code.AncillarySystemTransferInitiation => "ASTI",
                ExternalLocalInstrument1Code.BackupPayment => "BACP",
                ExternalLocalInstrument1Code.MandatedPayment => "MANP",
                ExternalLocalInstrument1Code.SettlementBankTransferInitiation => "SBTI",
                ExternalLocalInstrument1Code.PreauthorisedDirectDebitAccéléréAcceleratedClearing2DayOrdinaireNormalClearing4Day => "85",
                ExternalLocalInstrument1Code.PreauthorisedDirectDebitOrdinaireNormalClearing4Day => "08",
                ExternalLocalInstrument1Code.PreauthorisedDirectDebitVérifiéVerifiedClearing => "89",
                ExternalLocalInstrument1Code.RecoveredBillofExchangeorPromissoryNote => "60",
                ExternalLocalInstrument1Code.NonPreauthorisedDirectDebitRIBA => "RIBA",
                ExternalLocalInstrument1Code.PreauthorisedRevocableDirectDebit => "RIDO",
                ExternalLocalInstrument1Code.PreauthorisedRevocableUrgentDirectDebit => "RIDV",
                ExternalLocalInstrument1Code.PaymentsViaInternetOwnedByCurrence => "IDEAL",
                ExternalLocalInstrument1Code.InstantCreditTransferNotTimeCritical => "INSTNT01",
                ExternalLocalInstrument1Code.InstantCreditTransferTimeCritical => "INSTTC01",
                ExternalLocalInstrument1Code.PaymentsViaInternetOwnedByCurrenceUsingInstantCreditTransfer => "INSTIDEAL",
                ExternalLocalInstrument1Code.PaymentsViaInternetOwnedByCurrenceUsingInstantCreditTransferNotTimeCritical => "INSTNT01IDEAL",
                ExternalLocalInstrument1Code.PaymentsViaInternetOwnedByCurrenceUsingInstantCreditTransferTimeCritical => "INSTTC01IDEAL",
                ExternalLocalInstrument1Code.DutchDomesticBulkPayment => "NLDO",
                ExternalLocalInstrument1Code.DutchUrgentPayment => "NLUP",
                ExternalLocalInstrument1Code.PaymentsViaStandaardDigitaleNota => "SDN",
                ExternalLocalInstrument1Code.PaymentViaAcceptgiroOwnedByCurrence => "ACCEPT",
                ExternalLocalInstrument1Code.IncidentManagementCorrection => "ICMC",
                ExternalLocalInstrument1Code.DirectDebitInitiatedByTheGovernmentWithSpecialConditions => "NLGOV",
                ExternalLocalInstrument1Code.MassPaymentBeneficiary => "0090",
                ExternalLocalInstrument1Code.MassPaymentOurs => "0091",
                ExternalLocalInstrument1Code.MassPaymentShared => "0092",
                ExternalLocalInstrument1Code.StandingOrder => "0002",
                ExternalLocalInstrument1Code.OneOffAuthorisation => "0221",
                ExternalLocalInstrument1Code.OneOffAuthorisationCharities => "0224",
                ExternalLocalInstrument1Code.OneOffAuthorisationConstructionIndustry => "0226",
                ExternalLocalInstrument1Code.OneOffAuthorisationTuitionFees => "0225",
                ExternalLocalInstrument1Code.StandingAuthorisationCompanies => "0222",
                ExternalLocalInstrument1Code.StandingAuthorisationCompaniesWithoutDebtorRevocationRight => "0227",
                ExternalLocalInstrument1Code.StandingAuthorisationGeneral => "0220",
                ExternalLocalInstrument1Code.StandingAuthorisationLotteries => "0223",
                ExternalLocalInstrument1Code.ConvertedBankPayment => "0001",
                ExternalLocalInstrument1Code.BusinessPayment => "0000",
                ExternalLocalInstrument1Code.CrossBorderCustomerCreditTransfer => "IN",
                ExternalLocalInstrument1Code.Overnight => "ONCL",
                ExternalLocalInstrument1Code.PaymentWithERI => "PERI",
                ExternalLocalInstrument1Code.SameDayClearedPayments => "SDCL",
                ExternalLocalInstrument1Code.CoreNoRefund => "DDNR",
                ExternalLocalInstrument1Code.DirectDebitFixedAmount => "DDFA",
                ExternalLocalInstrument1Code.SEPADirectDebitCore => "CORE",
                ExternalLocalInstrument1Code.SEPAB2BDirectDebitAMI => "B2BAMIPM",
                ExternalLocalInstrument1Code.SEPABusinessToBusinessDirectDebit => "B2B",
                ExternalLocalInstrument1Code.SEPACoreD1DirectDebitAMI => "CR1AMIPM",
                ExternalLocalInstrument1Code.SEPACoreDirectDebitAMI => "CORAMIPM",
                ExternalLocalInstrument1Code.SEPADirectDebit1DaySettlement => "COR1",
                ExternalLocalInstrument1Code.SEPAFADirectDebitAMI => "FADAMIPM",
                ExternalLocalInstrument1Code.CLSClearedFXForEurex => "CLSCCPERX",
                ExternalLocalInstrument1Code.CLSClearedFXForLCH => "CLSCCPLCH",
                ExternalLocalInstrument1Code.InstantCreditTransfer => "INST",
                ExternalLocalInstrument1Code.AuthenticatedDirectDebit => "ADD",
                ExternalLocalInstrument1Code.UnauthenticatedDirectDebit => "UDD",
                ExternalLocalInstrument1Code.CashConcentrationIntragroup => "CCI",
                ExternalLocalInstrument1Code.BankTransfer => "BTR",
                ExternalLocalInstrument1Code.CheckSameDaySettlementWire => "CKS",
                ExternalLocalInstrument1Code.CustomerTransfer => "CTR",
                ExternalLocalInstrument1Code.CustomerTransferPlus => "CTP",
                ExternalLocalInstrument1Code.DepositToSendersAccount => "DEP",
                ExternalLocalInstrument1Code.FedFundsReturned => "FFR",
                ExternalLocalInstrument1Code.FedFundsSold => "FFS",
                ExternalLocalInstrument1Code.NonValueServiceMessage => "SVC",
                ExternalLocalInstrument1Code.DrawdownResponseValueToHonorADrawdownRequest => "DRW",
                ExternalLocalInstrument1Code.BankToBankDrawdownRequestOrResponseNonvalue => "DRB",
                ExternalLocalInstrument1Code.CustomerOrCorporateDrawdownRequestOrResponseNonvalue => "DRC",
                ExternalLocalInstrument1Code.InternationalACH => "IAT",
                ExternalLocalInstrument1Code.CashConcentrationOrDisbursementCorporateCounterparty => "CCD",
                ExternalLocalInstrument1Code.CorporateTradeExchange => "CTX",
                ExternalLocalInstrument1Code.PrearrangedPaymentOrDepositConsumerCounterparty => "PPD",
                ExternalLocalInstrument1Code.CustomerInitiatedEntry => "CIE",
                ExternalLocalInstrument1Code.RepresentedCheckEntry => "RCK",
                ExternalLocalInstrument1Code.AccountsReceivableCheck => "ARC",
                ExternalLocalInstrument1Code.InternetInitiatedEntry => "WEB",
                ExternalLocalInstrument1Code.PointOfPurchase => "POP",
                ExternalLocalInstrument1Code.PointOfSale => "POS",
                ExternalLocalInstrument1Code.TelephoneInitiatedEntry => "TEL",
                ExternalLocalInstrument1Code.InstantCreditTransferPreferred => "ITP",
                ExternalLocalInstrument1Code.CreditTransferPreferred => "CTP",
                ExternalLocalInstrument1Code.MultiDayPayment => "MDP",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
