//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for ExternalPersonIdentification1Code.  ISO2002 ID# _ame0hdp-Ed-ak6NoX_4Aeg_-1698163033.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ExternalPersonIdentification1Code"/>.
    /// </summary>
    public class ExternalPersonIdentification1CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<ExternalPersonIdentification1Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, ExternalPersonIdentification1Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                ExternalPersonIdentification1Code.AlienRegistrationNumber => "ARNU",
                ExternalPersonIdentification1Code.PassportNumber => "CCPT",
                ExternalPersonIdentification1Code.CustomerIdentificationNumber => "CUST",
                ExternalPersonIdentification1Code.DriversLicenseNumber => "DRLC",
                ExternalPersonIdentification1Code.EmployeeIdentificationNumber => "EMPL",
                ExternalPersonIdentification1Code.NationalIdentityNumber => "NIDN",
                ExternalPersonIdentification1Code.SocialSecurityNumber => "SOSE",
                ExternalPersonIdentification1Code.TelephoneNumber => "TELE",
                ExternalPersonIdentification1Code.TaxIdentificationNumber => "TXID",
                ExternalPersonIdentification1Code.PersonCommercialIdentification => "POID",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
