//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetSerializationGenerator for PaymentMethod3Code.  ISO2002 ID# _Z0aeYtp-Ed-ak6NoX_4Aeg_1813568342.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Codesets;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Codesets
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="PaymentMethod3Code"/>.
    /// </summary>
    public class PaymentMethod3CodeXmlAsyncWriter : ISubordinateXmlAsyncWriter<PaymentMethod3Code>
    {
        public virtual async Task WriteAsync(XmlWriter writer, PaymentMethod3Code valueBeingSerialized, string isoNamespace)
        {
            var valueToWrite = valueBeingSerialized switch
            {
                PaymentMethod3Code.Cheque => "CHK",
                PaymentMethod3Code.CreditTransfer => "TRF",
                PaymentMethod3Code.TransferAdvice => "TRA",
                _ => "_"
            };
            await writer.WriteStringAsync(valueToWrite);
        }
    }
}
