//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by SimpleTypeInteraceForExternalCodesetsGenerator for ActiveOrHistoricCurrencyCode.  ISO2002 ID# _bqIp6tp-Ed-ak6NoX_4Aeg_1823330336.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.
    /// This is declared to serialize on behalf of the codeset named &apos;ActiveOrHistoricCurrencyCode&apos; which does not relate to an enum value,
    /// but is instead maintaned externally. Details:
    /// A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 &quot;Codes for the representation of currencies and funds&quot;.
    /// </summary>
    public interface ActiveOrHistoricCurrencyCodeXmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<System.String>
    {
    }
}
