//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by SimpleTypeInteraceForExternalCodesetsGenerator for ExternalFinancialInstitutionIdentification1Code.  ISO2002 ID# _ame0gNp-Ed-ak6NoX_4Aeg_-1716707444.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.
    /// This is declared to serialize on behalf of the codeset named &apos;ExternalFinancialInstitutionIdentification1Code&apos; which does not relate to an enum value,
    /// but is instead maintaned externally. Details:
    /// Specifies the external financial institution identification scheme name code in the format of character string with a maximum length of 4 characters.
    /// The list of valid codes is an external code list published separately.
    /// External code sets can be downloaded from www.iso20022.org.
    /// </summary>
    public interface IExternalFinancialInstitutionIdentification1CodeXmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<System.String>
    {
    }
}
