//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by SimpleTypeInteraceGenerator for ISOYearMonth.  ISO2002 ID# _YYU64tp-Ed-ak6NoX_4Aeg_-1824134999.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.  Format information: 
    /// Month within a particular calendar year represented by YYYY-MM (ISO 8601).
    /// </summary>
    public interface IISOYearMonthXmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<System.UInt16>
    {
    }
}
