//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by SimpleTypeInteraceGenerator for Max2Fraction1NonNegativeNumber.  ISO2002 ID# _c8rdMY0iEemUAO64Q252gQ.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.  Format information: 
    /// Number of objects represented as a non negative decimal number, for example 1.1 or 8.0.
    /// </summary>
    public interface IMax2Fraction1NonNegativeNumberXmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<System.UInt64>
    {
    }
}
