//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by SimpleTypeInteraceGenerator for Max5000Binary.  ISO2002 ID# _TQbTyQEcEeCQm6a_G2yO_w_-655974114.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.  Format information: 
    /// Specifies a binary string with a maximum length of 5000 binary bytes.
    /// </summary>
    public interface IMax5000BinaryXmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<System.Byte[]>
    {
    }
}
