//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by SimpleTypeInteraceGenerator for Min1Max256Binary.  ISO2002 ID# _0kPi4d6jEeiwsev40qZGEQ.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.  Format information: 
    /// Specifies a binary string with a minimum length of 1 byte, and a maximum length of 256 bytes.
    /// </summary>
    public interface IMin1Max256BinaryXmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<System.Byte[]>
    {
    }
}
