//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by SimpleTypeInteraceGenerator for Min5Max16Binary.  ISO2002 ID# _TQlExAEcEeCQm6a_G2yO_w_-1295689418.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.  Format information: 
    /// Specifies a binary string with a minimum length of 5 bytes, and a maximum length of 16 bytes.
    /// </summary>
    public interface IMin5Max16BinaryXmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<System.Byte[]>
    {
    }
}
