//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by SimpleTypeInteraceGenerator for RateSourceText.  ISO2002 ID# _n-vS8JULEeak6e8_Fc5fQg.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.  Format information: 
    /// Specifies a rate source.
    /// 
    /// The values to be used for the settlement rate source are published in Annex A of the 1998 FX and Currency
    /// Option Definitions (the FX definitions, as published by the International Swaps and Derivatives Association,
    /// Inc., the Emerging Markets Traders Association and the Foreign Exchange Committee) as amended and
    /// supplemented from time to time.
    /// </summary>
    public interface IRateSourceTextXmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<System.String>
    {
    }
}
