//
// This is a generated template. Edit is allowed.  Please remove this line when first edit is made.
//
// Generated by UserDefinedSerializationClassGenerator for SupplementaryDataContents1.  ISO2002 ID# _YWZBMdp-Ed-ak6NoX_4Aeg_-375411192.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.UserDefined;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.UserDefined
{
    /// <summary>
    /// Implemented by the provider of serialization for this data type.  Format information: 
    /// Technical supplementary data structure that allows to specify any valid XML Structure (e.g. through an XML Schema). The property namespace is set to &apos;any&apos;. 
    /// The content of the supplementary data MUST NOT be validated by the receiver (processContent=lax).
    /// </summary>
    public class SupplementaryDataContents1XmlAsyncWriter : ISimpleTypeSubordinateXmlAsyncWriter<SupplementaryDataContents1>
    {
        
        // Create a constructor with an injected logger if contents are modified during serialization.
        
        /// <summary>
        /// Write the value to the output the way ISO20022 says a &apos;SupplementaryDataContents1&apos; should be formatted.
        /// Coerce the value when possible or truncate text that is too long.
        /// Can be overridden by subclass with inheritance.
        /// </summary>
        public virtual Task WriteAsync(XmlWriter writer, SupplementaryDataContents1 value, string isoNamespace)
        {
            // Underlying library does not supply a property to write, implement later.
            // writer.WriteValue( value );
            return Task.CompletedTask;
        }
    }
}
