//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by MainComponentSerializerGenerator for CustomerPaymentReversalV11.  ISO2002 ID# _rUXm6dcBEeq_l4BJLVUF2Q.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.pain;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Async.Writers.pain
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="CustomerPaymentReversalV11"/>.
    /// </summary>
    public class CustomerPaymentReversalV11XmlAsyncWriter : ContainerXmlAsyncWriter<CustomerPaymentReversalV11>
            , ISubordinateXmlAsyncWriter<CustomerPaymentReversalV11>
    {
        public CustomerPaymentReversalV11XmlAsyncWriter(
            
            // Injected dependencies
            
            ISubordinateXmlAsyncWriter<GroupHeader88> groupHeader,
            ISubordinateXmlAsyncWriter<OriginalGroupHeader16> originalGroupInformation,
            ISubordinateXmlAsyncWriter<OriginalPaymentInstruction41> originalPaymentInformationAndReversal,
            ISubordinateXmlAsyncWriter<SupplementaryData1> supplementaryData
        )
        : base (
            
            // Initalizing constituent members
            
                new MemberXmlAsyncWriter<CustomerPaymentReversalV11,GroupHeader88>
                (
                    "GrpHdr",
                    groupHeader,
                    parent => parent.GroupHeader
                ),
                
                new MemberXmlAsyncWriter<CustomerPaymentReversalV11,OriginalGroupHeader16>
                (
                    "OrgnlGrpInf",
                    originalGroupInformation,
                    parent => parent.OriginalGroupInformation
                ),
                
                new MemberXmlAsyncWriter<CustomerPaymentReversalV11,OriginalPaymentInstruction41>
                (
                    "OrgnlPmtInfAndRvsl",
                    originalPaymentInformationAndReversal,
                    parent => parent.OriginalPaymentInformationAndReversal
                ),
                
                new MemberXmlAsyncWriter<CustomerPaymentReversalV11,SupplementaryData1>
                (
                    "SplmtryData",
                    supplementaryData,
                    parent => parent.SupplementaryData
                )
                
        )
        {
        }
    }
}
