//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentSerializationGenerator for ExchangeRate1.  ISO2002 ID# _t0booVkyEeGeoaLUQk__nA_667162887.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Codesets;
using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.Components
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ExchangeRate1"/>.
    /// </summary>
    public class ExchangeRate1XmlAsyncWriter : ISubordinateXmlAsyncWriter<ExchangeRate1>
    {
        // Injected dependencies for serialization of each member data type
        private readonly ActiveOrHistoricCurrencyCodeXmlAsyncWriter unitCurrency;
        private readonly BaseOneRateXmlAsyncWriter exchangeRate;
        private readonly ExchangeRateType1CodeXmlAsyncWriter rateType;
        private readonly Max35TextXmlAsyncWriter contractIdentification;
        
        /// <summary>
        /// Construct using an injected writer for each member.
        /// </summary>
        public ExchangeRate1XmlAsyncWriter
        (
            ActiveOrHistoricCurrencyCodeXmlAsyncWriter unitCurrency,
            BaseOneRateXmlAsyncWriter exchangeRate,
            ExchangeRateType1CodeXmlAsyncWriter rateType,
            Max35TextXmlAsyncWriter contractIdentification
        )
        {
            this.unitCurrency = unitCurrency;
            this.exchangeRate = exchangeRate;
            this.rateType = rateType;
            this.contractIdentification = contractIdentification;
        }
        public async Task WriteAsync(XmlWriter writer, ExchangeRate1 valueBeingSerialized, string isoNamespace)
        {
            // UnitCurrency Optional ActiveOrHistoricCurrencyCode string
            if ( valueBeingSerialized.UnitCurrency is string populatedUnitCurrency)
            {
                await writer.WriteStartElementAsync(null, "UnitCcy", isoNamespace );
                await unitCurrency.WriteAsync(writer, populatedUnitCurrency, isoNamespace);
                await writer.WriteEndElementAsync();
            }
            // ExchangeRate Optional BaseOneRate System.Decimal
            if ( valueBeingSerialized.ExchangeRate is System.Decimal populatedExchangeRate)
            {
                await writer.WriteStartElementAsync(null, "XchgRate", isoNamespace );
                await exchangeRate.WriteAsync(writer, populatedExchangeRate, isoNamespace);
                await writer.WriteEndElementAsync();
            }
            // RateType Optional ExchangeRateType1Code ExchangeRateType1Code
            if ( valueBeingSerialized.RateType is ExchangeRateType1Code populatedRateType)
            {
                await writer.WriteStartElementAsync(null, "RateTp", isoNamespace );
                await rateType.WriteAsync(writer, populatedRateType, isoNamespace);
                await writer.WriteEndElementAsync();
            }
            // ContractIdentification Optional Max35Text System.String
            if ( valueBeingSerialized.ContractIdentification is System.String populatedContractIdentification)
            {
                await writer.WriteStartElementAsync(null, "CtrctId", isoNamespace );
                await contractIdentification.WriteAsync(writer, populatedContractIdentification, isoNamespace);
                await writer.WriteEndElementAsync();
            }
        }
    }
}
