//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceSerializationGenerator for DateTime.  ISO2002 ID# _fPH6g5lhEeeE1Ya-LgRsuQ.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Choices.DateAndDateTime2Choice;
using BeneficialStrategies.Iso20022.Codesets;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Writers.Choices.DateAndDateTime2Choice
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="DateTime"/>.
    /// </summary>
    public class DateAndDateTime2ChoiceDateTimeXmlAsyncWriter : ISubordinateXmlAsyncWriter<DateTime>
    {
        // Injected dependencies for serialization of each member data type
        private readonly ISODateTimeXmlAsyncWriter value;
        
        /// <summary>
        /// Construct using an injected writer for each member.
        /// </summary>
        public DateAndDateTime2ChoiceDateTimeXmlAsyncWriter
        (
            ISODateTimeXmlAsyncWriter value
        )
        {
            this.value = value;
        }
        public async Task WriteAsync(XmlWriter writer, DateTime valueBeingSerialized, string isoNamespace)
        {
            // Value Required ISODateTime System.DateTime
            await writer.WriteStartElementAsync(null, "DtTm", isoNamespace );
            await value.WriteAsync(writer, valueBeingSerialized.Value, isoNamespace);
            await writer.WriteEndElementAsync();
        }
    }
}
