//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceSerializationGenerator for CashAccountType2Choice.  ISO2002 ID# _sb6WgFkyEeGeoaLUQk__nA_1768299331.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Choices.CashAccountType2Choice;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.Choices.CashAccountType2Choice;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Choices
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="CashAccountType2Choice_"/>.
    /// </summary>
    public class CashAccountType2ChoiceXmlAsyncWriter : ISubordinateXmlAsyncWriter<CashAccountType2Choice_>
    {
        private readonly CashAccountType2ChoiceCodeXmlAsyncWriter code;
        private readonly CashAccountType2ChoiceProprietaryXmlAsyncWriter proprietary;
        
        /// <summary>
        /// Construct using an injected writer for each member.
        /// </summary>
        public CashAccountType2ChoiceXmlAsyncWriter
        (
            CashAccountType2ChoiceCodeXmlAsyncWriter code,
            CashAccountType2ChoiceProprietaryXmlAsyncWriter proprietary
        )
        {
            this.code = code;
            this.proprietary = proprietary;
        }
        public Task WriteAsync(XmlWriter writer, CashAccountType2Choice_ valueBeingSerialized, string isoNamespace)
        {
            return valueBeingSerialized switch
            {
                Code _code => this.code.WriteAsync( writer, _code, isoNamespace ),
                Proprietary _proprietary => this.proprietary.WriteAsync( writer, _proprietary, isoNamespace ),
                _ => throw new InvalidCastException( $"Data type of {valueBeingSerialized.GetType().FullName} has no corresponding serializer.")
            };
        }
    }
}
