//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceSerializationGenerator for CategoryPurpose1Choice.  ISO2002 ID# _THaa5Np-Ed-ak6NoX_4Aeg_1223014142.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Choices.CategoryPurpose1Choice;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.Choices.CategoryPurpose1Choice;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Choices
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="CategoryPurpose1Choice_"/>.
    /// </summary>
    public class CategoryPurpose1ChoiceXmlAsyncWriter : ISubordinateXmlAsyncWriter<CategoryPurpose1Choice_>
    {
        private readonly CategoryPurpose1ChoiceCodeXmlAsyncWriter code;
        private readonly CategoryPurpose1ChoiceProprietaryXmlAsyncWriter proprietary;
        
        /// <summary>
        /// Construct using an injected writer for each member.
        /// </summary>
        public CategoryPurpose1ChoiceXmlAsyncWriter
        (
            CategoryPurpose1ChoiceCodeXmlAsyncWriter code,
            CategoryPurpose1ChoiceProprietaryXmlAsyncWriter proprietary
        )
        {
            this.code = code;
            this.proprietary = proprietary;
        }
        public Task WriteAsync(XmlWriter writer, CategoryPurpose1Choice_ valueBeingSerialized, string isoNamespace)
        {
            return valueBeingSerialized switch
            {
                Code _code => this.code.WriteAsync( writer, _code, isoNamespace ),
                Proprietary _proprietary => this.proprietary.WriteAsync( writer, _proprietary, isoNamespace ),
                _ => throw new InvalidCastException( $"Data type of {valueBeingSerialized.GetType().FullName} has no corresponding serializer.")
            };
        }
    }
}
