//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceSerializationGenerator for CreditorReferenceType1Choice.  ISO2002 ID# _T3_jStp-Ed-ak6NoX_4Aeg_651436639.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Choices.CreditorReferenceType1Choice;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.Choices.CreditorReferenceType1Choice;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Choices
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="CreditorReferenceType1Choice_"/>.
    /// </summary>
    public class CreditorReferenceType1ChoiceXmlAsyncWriter : ISubordinateXmlAsyncWriter<CreditorReferenceType1Choice_>
    {
        private readonly CreditorReferenceType1ChoiceCodeXmlAsyncWriter code;
        private readonly CreditorReferenceType1ChoiceProprietaryXmlAsyncWriter proprietary;
        
        /// <summary>
        /// Construct using an injected writer for each member.
        /// </summary>
        public CreditorReferenceType1ChoiceXmlAsyncWriter
        (
            CreditorReferenceType1ChoiceCodeXmlAsyncWriter code,
            CreditorReferenceType1ChoiceProprietaryXmlAsyncWriter proprietary
        )
        {
            this.code = code;
            this.proprietary = proprietary;
        }
        public Task WriteAsync(XmlWriter writer, CreditorReferenceType1Choice_ valueBeingSerialized, string isoNamespace)
        {
            return valueBeingSerialized switch
            {
                Code _code => this.code.WriteAsync( writer, _code, isoNamespace ),
                Proprietary _proprietary => this.proprietary.WriteAsync( writer, _proprietary, isoNamespace ),
                _ => throw new InvalidCastException( $"Data type of {valueBeingSerialized.GetType().FullName} has no corresponding serializer.")
            };
        }
    }
}
