//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceSerializationGenerator for DocumentLineType1Choice.  ISO2002 ID# __hXr4abkEeKvUvwX_r3tzA.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Choices.DocumentLineType1Choice;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.Choices.DocumentLineType1Choice;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Choices
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="DocumentLineType1Choice_"/>.
    /// </summary>
    public class DocumentLineType1ChoiceXmlAsyncWriter : ISubordinateXmlAsyncWriter<DocumentLineType1Choice_>
    {
        private readonly DocumentLineType1ChoiceCodeXmlAsyncWriter code;
        private readonly DocumentLineType1ChoiceProprietaryXmlAsyncWriter proprietary;
        
        /// <summary>
        /// Construct using an injected writer for each member.
        /// </summary>
        public DocumentLineType1ChoiceXmlAsyncWriter
        (
            DocumentLineType1ChoiceCodeXmlAsyncWriter code,
            DocumentLineType1ChoiceProprietaryXmlAsyncWriter proprietary
        )
        {
            this.code = code;
            this.proprietary = proprietary;
        }
        public Task WriteAsync(XmlWriter writer, DocumentLineType1Choice_ valueBeingSerialized, string isoNamespace)
        {
            return valueBeingSerialized switch
            {
                Code _code => this.code.WriteAsync( writer, _code, isoNamespace ),
                Proprietary _proprietary => this.proprietary.WriteAsync( writer, _proprietary, isoNamespace ),
                _ => throw new InvalidCastException( $"Data type of {valueBeingSerialized.GetType().FullName} has no corresponding serializer.")
            };
        }
    }
}
