//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceSerializationGenerator for MandateClassification1Choice.  ISO2002 ID# _JThtg2oDEearR-CA7eRZXQ.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Choices.MandateClassification1Choice;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.Choices.MandateClassification1Choice;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Choices
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="MandateClassification1Choice_"/>.
    /// </summary>
    public class MandateClassification1ChoiceXmlAsyncWriter : ISubordinateXmlAsyncWriter<MandateClassification1Choice_>
    {
        private readonly MandateClassification1ChoiceCodeXmlAsyncWriter code;
        private readonly MandateClassification1ChoiceProprietaryXmlAsyncWriter proprietary;
        
        /// <summary>
        /// Construct using an injected writer for each member.
        /// </summary>
        public MandateClassification1ChoiceXmlAsyncWriter
        (
            MandateClassification1ChoiceCodeXmlAsyncWriter code,
            MandateClassification1ChoiceProprietaryXmlAsyncWriter proprietary
        )
        {
            this.code = code;
            this.proprietary = proprietary;
        }
        public Task WriteAsync(XmlWriter writer, MandateClassification1Choice_ valueBeingSerialized, string isoNamespace)
        {
            return valueBeingSerialized switch
            {
                Code _code => this.code.WriteAsync( writer, _code, isoNamespace ),
                Proprietary _proprietary => this.proprietary.WriteAsync( writer, _proprietary, isoNamespace ),
                _ => throw new InvalidCastException( $"Data type of {valueBeingSerialized.GetType().FullName} has no corresponding serializer.")
            };
        }
    }
}
