//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceSerializationGenerator for Purpose2Choice.  ISO2002 ID# _P6qyHtp-Ed-ak6NoX_4Aeg_-1283223379.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Choices.Purpose2Choice;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.Choices.Purpose2Choice;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Choices
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="Purpose2Choice_"/>.
    /// </summary>
    public class Purpose2ChoiceXmlAsyncWriter : ISubordinateXmlAsyncWriter<Purpose2Choice_>
    {
        private readonly Purpose2ChoiceCodeXmlAsyncWriter code;
        private readonly Purpose2ChoiceProprietaryXmlAsyncWriter proprietary;
        
        /// <summary>
        /// Construct using an injected writer for each member.
        /// </summary>
        public Purpose2ChoiceXmlAsyncWriter
        (
            Purpose2ChoiceCodeXmlAsyncWriter code,
            Purpose2ChoiceProprietaryXmlAsyncWriter proprietary
        )
        {
            this.code = code;
            this.proprietary = proprietary;
        }
        public Task WriteAsync(XmlWriter writer, Purpose2Choice_ valueBeingSerialized, string isoNamespace)
        {
            return valueBeingSerialized switch
            {
                Code _code => this.code.WriteAsync( writer, _code, isoNamespace ),
                Proprietary _proprietary => this.proprietary.WriteAsync( writer, _proprietary, isoNamespace ),
                _ => throw new InvalidCastException( $"Data type of {valueBeingSerialized.GetType().FullName} has no corresponding serializer.")
            };
        }
    }
}
