//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AmountSerializationGenerator for ActiveOrHistoricCurrencyAnd20DecimalAmount.  ISO2002 ID# _uJAHQMz2EeufhKfUxzsnrQ.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Amounts;
using BeneficialStrategies.Iso20022.Codesets;
using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Codesets;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Amounts
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="ActiveOrHistoricCurrencyAnd20DecimalAmount"/>.
    /// </summary>
    public class ActiveOrHistoricCurrencyAnd20DecimalAmountXmlAsyncWriter : ISubordinateXmlAsyncWriter<ActiveOrHistoricCurrencyAnd20DecimalAmount>
    {
        public async Task WriteAsync(XmlWriter writer, ActiveOrHistoricCurrencyAnd20DecimalAmount valueBeingSerialized, string isoNamespace)
        {
            await writer.WriteAttributeStringAsync( null, "Currency", isoNamespace, valueBeingSerialized.Currency.ToString() );
            await writer.WriteStringAsync( valueBeingSerialized.Amount.ToString());
        }
    }
}
