//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AmountSerializationGenerator for RestrictedFINActiveOrHistoricCurrencyAndAmount.  ISO2002 ID# _XY_k3tp-Ed-ak6NoX_4Aeg_1054967173.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using BeneficialStrategies.Iso20022.Amounts;
using BeneficialStrategies.Iso20022.Codesets;
using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.Serialization.Xml.Codesets;
using BeneficialStrategies.Iso20022.Serialization.Xml.Writers.SimpleTypes;
using System.Xml;

namespace BeneficialStrategies.Iso20022.Serialization.Xml.Amounts
{
    /// <summary>
    /// Performs the XML serialization faithful to ISO20002 standards for <seealso cref="RestrictedFINActiveOrHistoricCurrencyAndAmount"/>.
    /// </summary>
    public class RestrictedFINActiveOrHistoricCurrencyAndAmountXmlAsyncWriter : ISubordinateXmlAsyncWriter<RestrictedFINActiveOrHistoricCurrencyAndAmount>
    {
        public async Task WriteAsync(XmlWriter writer, RestrictedFINActiveOrHistoricCurrencyAndAmount valueBeingSerialized, string isoNamespace)
        {
            await writer.WriteAttributeStringAsync( null, "Currency", isoNamespace, valueBeingSerialized.Currency.ToString() );
            await writer.WriteStringAsync( valueBeingSerialized.Amount.ToString());
        }
    }
}
